name = "TableLogger"
uuid = "72b659bb-f61b-4d0d-9dbb-0f81f57d8545"
authors = ["Ole Kröger <o.kroeger@opensourc.es> and contributors"]
version = "0.1.0"

[deps]
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"

[compat]
Formatting = "0.4"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
